- name: CLC | Create WWW Group
  clc_group:
    name: WWW
    location: UC1
    state: present

- name: Generate Password
  command: openssl rand -base64 15
  register: serverpass
  changed_when: False

- name: CLC | Build LAMP Server if Needed
  clc_server:
    name: www
    location: UC1
    template: ubuntu-16-64
    password: "{{ serverpass.stdout }}"
    exact_count: 3
    group: WWW
    count_group: WWW
    cpu: 1
    memory: 1
    storage_type: standard
  register: apache

- name: CLC | Add public ipaddress
  clc_publicip:
    server_ids: "{{ item.name }}"
    ports:
      - "{{ listen_port }}"
    protocol: TCP
    state: present
  with_items: "{{apache.servers}}"
  when: ("{{ public }}" == 'true')

- name: Wait for SSH Services to Become Available
  command: sleep 15

- name: Add New Servers to an inventory
  add_host:
    name={{ item.name }}
    ansible_ssh_host={{ item.ipaddress }}
    ansible_ssh_user=root
    ansible_ssh_pass={{ serverpass.stdout }}
    groupname=apache
  with_items: "{{ apache.servers }}"
